CREATE OR REPLACE TRIGGER studenti_bi
BEFORE INSERT ON studenti
FOR EACH ROW
BEGIN
    SELECT studenti_seq.NEXTVAL INTO :NEW.id_student FROM dual;
END;
/

CREATE OR REPLACE TRIGGER profesori_bi
BEFORE INSERT ON profesori
FOR EACH ROW
BEGIN
    SELECT profesori_seq.NEXTVAL INTO :NEW.id_profesor FROM dual;
END;
/

CREATE OR REPLACE TRIGGER note_bi
BEFORE INSERT ON nota
FOR EACH ROW
BEGIN
    SELECT note_seq.NEXTVAL INTO :NEW.id_nota FROM dual;
END;
/

CREATE OR REPLACE TRIGGER materii_bi
BEFORE INSERT ON materii
FOR EACH ROW
BEGIN
    SELECT materii_seq.NEXTVAL INTO :NEW.id_materie FROM dual;
END;
/

COMMIT;

EXIT;