CREATE SEQUENCE studenti_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE profesori_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE note_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE materii_seq START WITH 1 INCREMENT BY 1;